<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>StarTooth</AssemblyTitle>
    <Product>StarTooth</Product>
    <Company>Stefan Lohmaier</Company>
    <Copyright>Copyright (c) 2026 Stefan Lohmaier</Copyright>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
